import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Header } from "./components/ui/header";
import Home from "./pages/Home/Home";
import News from "./pages/News/News";
import MoviePosters from "./pages/Movies/MoviePosters";
import { FAQ } from "./pages/Home/FAQ";
import AdminMain from "./pages/Admin/Main"
import Account from "./pages/Authentication/Account";
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
import Users from "./pages/Admin/Users";
import Movies from "./pages/Admin/Movies";
import Seanses from "./pages/Admin/Seanses";
import CinemasManagement from "./pages/Admin/CinemaManagement";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
import AuthButton from "./components/ui/AuthButton";
import RegisterButton from "./components/ui/RegisterButton";
import Users from "./pages/Admin/Users/Users";
import MovieManagement from "./pages/Admin/MovieManagement";
import SeanseManagement from "./pages/Admin/SeanseManagement";
import { Footer } from "./components/ui/footer";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/OT_19_Prices_Entity_CRUD

function App() {
    return (
        <BrowserRouter>
            <Header/>
                <Routes>
                    <Route path="/" element={<Home />}></Route>
                    <Route path="/admin/main" element={<AdminMain />}></Route>
                    <Route path="/admin/cinema_management" element={<CinemasManagement />}></Route>
                    <Route path="/admin/users" element={<Users />}></Route>                  
                    <Route path="/admin/movies" element={<Movies />}></Route>
                    <Route path="/admin/seanses" element={<Seanses />}></Route>
                    <Route path="/news/news" element={<News/>}></Route>
                    <Route path="/movies/movieposters" element={<MoviePosters/>}></Route>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                        <Route path="/admin/main" element={<AdminMain/>}></Route>
                        <Route path="/admin/users" element={<Users />}></Route>                  
                        <Route path="/admin/moviemanagement" element={<MovieManagement/>}></Route>                       
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/OT_19_Prices_Entity_CRUD
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
                    <Route path="/home/faq" element={<FAQ/>}></Route>                     
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                        <Route path="/home/faq" element={<FAQ/>}></Route> 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/OT_19_Prices_Entity_CRUD
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
                    <Route path="/account" element={<Account />}></Route>
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                        <Route path="/admin/seansemanagement" element={<SeanseManagement/>}></Route>               
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/OT_19_Prices_Entity_CRUD
                                        
                </Routes>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                </div>    
                <Footer/>           
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/OT_19_Prices_Entity_CRUD
        </BrowserRouter>
    );
}

export default App;
